- hosts: all
  sudo: yes
  tasks:
    - name: Install docker
      apt:
          name: docker.io
          state: present

    - name: Add ras group
      group:
          name: ras
          state: present

    - name: Add ras user
      user:
          name: ras
          password: "{{ 'ras' | password_hash('sha512') }}"
          group: ras
          groups: docker, sudo
          create_home: yes
          shell: /bin/bash
          state: present

    - name: Add SSH keys
      authorized_key:
          user: ras
          state: present
          key: "{{ lookup('file', 'authorized_keys') }}"

    - name: Add ROS apt key
      apt_key:
          keyserver: ha.pool.sks-keyservers.net
          id: 421C365BD9FF1F717815A3895523BAEEB01FA116

    - name: Add ROS apt repo
      apt_repository:
          state: present
          filename: ros-latest
          repo: deb http://packages.ros.org/ros/ubuntu bionic main

    - name: Install ROS
      apt:
          name: ros-melodic-ros-base
          update_cache: yes
          state: present
